version: '3.8'

services:
  backend:
    build: ./backend
    command: python manage.py runserver 0:8000
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      ./.backend.env
    depends_on:
      - database

  database:
    image: postgres:12-alpine
    volumes:
      - ./database/data/:/var/lib/postgresql/data/
    env_file:
      - ./.db.env